name: "Bicep Deploy Workflow"

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  subscriptionId: 6a93b522-87de-439e-a105-0422c1795f27

jobs:
  bicepArmDeploy:
    name: Deploy Bicep using Azure CLI
    runs-on: ubuntu-latest
    env:
      location: Australia East
      resource_group_name: rg-bicep-githubactions

    steps:
      - uses: actions/checkout@v3

      - name: Login to Azure Environment
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Resource Group ${{ env.resource_group_name}}
        uses: Azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ env.subscriptionid}}
          region: Australia East
          template: ./bicep-templates/resourcegroup.bicep
          parameters:
            location="${{ env.location }}"
            resourceGroupName=${{ env.resource_group_name }}
          deploymentName: ${{ env.resource_group_name }}

 





